### ISSUE TITLE
Compatibility with Nextcloud 28 and 29

### ISSUE THREAD

**Issue by CodeShakingSheep** [sualko/cloud_piwik#101]
### Expected behavior
App should be officially compatible with Nextcloud 28.

### Actual behavior
App is marked as "untested" on Nextcloud 28 installation.
![image](https://github.com/sualko/cloud_piwik/assets/19874562/4bc5f22a-2006-487b-bf44-519ffcd2f90d)

### Steps to reproduce the behavior
1. Upgrade Nextcloud to version 28.
2. Check App section

### Environment
- **App version:** 0.12.0
- **Nextcloud version:** 28.0.1 
- **Browser vendor and version:** Brave Version 1.62.156 Chromium: 121.0.6167.139 (Official Build) unknown (64-bit)
- **Any browser plugins enabled?** No
- **Is your Matomo installation working as expected?** Yes

### Logs
None

**Comment by ventoux84** [comment]
Upgrading to Nextcloud 28.0.4 disable Piwik/Matomo app. It's not compatible with the new version.

**Comment by CodeShakingSheep** [comment]
There is already a PR for that, see https://github.com/sualko/cloud_piwik/pull/102 . @sualko Can we get this merged and have a new version released?

**Comment by ventoux84** [comment]
Thanks !
I added his new line into info.xml, and it works well.

**Comment by stepcellwolf** [comment]
@ventoux84 When there will be merge available with the Nextcloud 29 compatibility?

**Comment by ventoux84** [comment]
Maybe today, maybe tomorrow, maybe the day after.

Edit the info.xml yourself
