### ISSUE TITLE
Trying to get property of non-object / array_flip(): Can only flip STRING and INTEGER values!

### ISSUE THREAD

**Issue by alexhass** [sualko/cloud_piwik#39]
> Trying to get property of non-object at /var/www/nextcloud/apps/piwik/appinfo/app.php#17
> 
> array_flip(): Can only flip STRING and INTEGER values! at /var/www/nextcloud/lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php#343

This errors (tons of them) appear in log in v12 once piwik get enabled.

**Comment by sualko** [comment]
Is the app working correctly?

**Comment by yamlfd** [comment]
There are errors! So - no.

**Comment by sualko** [comment]
Can you post your app config and PHP version?

**Comment by yamlfd** [comment]
Debian 9 / Apache 2.4 / PHP 7.0

- Side ID: 1
- URL: //www.example.com/piwik/

**Comment by yamlfd** [comment]
Have you ever tested the addon with php 7?

**Comment by sualko** [comment]
> Have you ever tested the addon with php 7?

Yes, my private Nextcloud instance is running fine with php 7 and piwik. Try to add http or https to your piwik url.

**Comment by keinkurt** [comment]
I have the same error messages.

Running: Debian 8 / nginx 1.10.3 / PHP 7.0.21 / Nextcloud 12.0.1

Piwik Config:
* Site ID: 2
* URL: https://piwik.example.com

**Comment by yamlfd** [comment]
Sualko: have you checked your server log? If not, please see the errors there.

**Comment by funkytraffic** [comment]
Confirming the error on Nextcloud 12.0.3

Data entered in the backend is not saved.

Trying to get property of non-object at /html/zfd-teamplattform/apps/piwik/appinfo/app.php#17

array_flip(): Can only flip STRING and INTEGER values! at /html/zfd-teamplattform/lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php#343

**Comment by funkytraffic** [comment]
The simple solution is to disable the Adblocker, Firefox/ublock in my case.

**Comment by yamlfd** [comment]
Adblock does not block Piwik!

**Comment by funkytraffic** [comment]
Sorry @yamlfd, you are correct.

**Comment by sualko** [comment]
This is probably related to nextcloud/server#5179. I will add the "dirty" fix and hope it works for you guys.
