### ISSUE TITLE
app not working in owncloud 9.1.6

### ISSUE THREAD

**Issue by fbassas** [sualko/cloud_piwik#43]
Hi,
we have installed your app in an owncloud 9.1.6 server and piwik in another one.
From owncloud admin we get "piwik tracking" section and we fill it with piwik server information:
           Sire ID: 1
           Piwik url: //piwik.mm.nn (we have tried http://piwik.mm.nn as well)
We have also add "ProxyPass /piwik/ http://piwikct.upc.edu/" in owncloud's apache VirtualHost
At piwik server, we have created a site id 1 for owncloud.

The thing is that nothing is tracked. No trace is shown of piwik at owncloud logs, apache logs.
It seems like piwik is disablet, but it isn't.
What else can I try? Have I missed something?

**Comment by fbassas** [comment]
I get this:
Loading failed for the <script> with source “http://piwikct.mm.nn/piwik.js”.
Content Security Policy: Page parameters  have blocked resource loading at http://piwikct.mm.nn/piwik.js («script-src https://owncloud.mm.nn https://piwikct.mm.nn 'unsafe-eval'»).
Is it a problem with the browser?

**Comment by sualko** [comment]
It fails, because in the csp https is used, but the script is requested via http. I'm not sure why this happens, but if you have a proxy pass, just use `/piwik/` as piwik url.

**Comment by fbassas** [comment]
Now works. Thanks @sualko 
Anyway, we want to track desktop connections as well, so we guess it'll be better use log analysis script.
Are we getting the same statistics info with log analysis script than via app?

**Comment by sualko** [comment]
> Are we getting the same statistics info with log analysis script than via app?

Sorry, I don't have experience with that, but you could also use NC Hooks to log information to piwik.
