### ISSUE TITLE
array_flip errors usind nc 12.0.5

### ISSUE THREAD

**Issue by tuxmaster** [sualko/cloud_piwik#46]
As soon as I install the plug in massive errors about:

> {PHP} array_flip(): Can only flip STRING and INTEGER values! at /var/www/html/owncloud/lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php#343

will be logged. I use PHP 7.1
Deactivate the app will not help. I Must complete remove it.

**Comment by sualko** [comment]
Probably related to #39. Can you post some more information about your installation? Which piwik settings do you use? How is your piwik/nc setup? App version? etc.

**Comment by tuxmaster** [comment]
App version: 0.3.2
NC: 12.0.5
OS: Both CentOS 7.4
PHP: Both via fpm 7.1
Piwik version: 3.3.0
Both apps use https

In the webconsole I can read:
fail to load /settings/admin/statistik.terrortux.de/piwik.js But not why.

**Comment by sualko** [comment]
> In the webconsole I can read:
fail to load /settings/admin/statistik.terrortux.de/piwik.js But not why.

Can you try to prepend `https://` to your piwik url?

**Comment by tuxmaster** [comment]
Yes it will fix it.
