### ISSUE TITLE
NC 13 don't save the settings after update from NC12

### ISSUE THREAD

**Issue by tuxmaster** [sualko/cloud_piwik#47]
After update from NC 12 to 13 the piwik settings are lost.
When I set the settings again and reload the page, the settings are gone gain.
No error messages are logged.
I use version 0.3.2 of the module.

**Comment by sualko** [comment]
Can you check your js console?

**Comment by tuxmaster** [comment]
The only error that will shown, when the config page is loaded are:

> Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
> Ressourcen-Adresse: https://FOO/core/vendor/core.js?v=207905fe-0
> Source-Map-Adresse: purify.min.js.map

**Comment by alaunay** [comment]
I'm having the same problem, unsure if /all/ the messages are relevant:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-OHZRemppazZZT0VTaU4xNURoV3FBU0dBa3lZcWo3dU9FbVBzWjFTNUFLQT06cEpvQTNXRlhNS1YzN2E4b1NrVExVeG5LK2tKLzdmcTVVVG1sVVQyTWJjZz0=' https://cloud.domain.tld https://piwik.domain.tld 'unsafe-eval'”). Source: (function (ERROR) {

    const V8_STACK_....
additional:1
Loading failed for the <script> with source “https://cloud.domain.tld/apps/piwik/js/track.js?v=afb27704-4”.
additional:41
Loading failed for the <script> with source “https://cloud.domain.tld/apps/piwik/js/settings-admin.js?v=afb27704-4”.
additional:51
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Logging system initialised at Sat Mar 10 2018 12:26:23 GMT+0100 (CET)
common.js:206:17
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://cloud.domain.tld/core/vendor/core.js?v=afb27704-4
Source Map URL: purify.min.js.map

```

Don't hesitate if I can help in any way.

**Comment by sualko** [comment]
I changed the way this app stores all settings and therefore your error should be gone. Please wait for the next release and report if the error still exists.
