### ISSUE TITLE
Not able to Save Page-ID and URL

### ISSUE THREAD

**Issue by mmuetze** [sualko/cloud_piwik#53]
I'm not able to save the Page-ID and URL.
There is no save-button and if I leave the page and come back, the fields are empty again.

Best regards

**Comment by Happyfeet01** [comment]
I use the beta, but no save button.

**Comment by sualko** [comment]
It should save if you leave the input. Can you provide some more information, like your browser vendor, javascript log and so on?

**Comment by timscha** [comment]
For me it's still not working.
Firefox 59

Javascript console (in German, sorry):

Laden fehlgeschlagen für das <script> mit der Quelle "https://mydomain.com/apps/piwik/js/settings/admin.js?v=0983e5c3-5".
additional:58
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://mydomain/core/vendor/core.js?v=0983e5c3-5
Source-Map-Adresse: purify.min.js.map[Weitere Informationen]

**Comment by mmuetze** [comment]
I don't see any input for Page-ID and URL now after updating :(

**Comment by timscha** [comment]
@mmuetze I had to deactive and reactive the app. After that, I saw the options.

**Comment by mmuetze** [comment]
Fields are still empty after reload.

**Comment by sualko** [comment]
Sorry guys, but it's not enough information to reproduce the error. I tested the plugin with NC 13, Firefox 59 and Chrome 64.0.3282.189 with no problems. Please provide your browser vendor, version, extensions, the NC version, log, the web server log, javascript log and network log if a file fails to load.

**Comment by timscha** [comment]
It work now. I had to deactive my adblocker (Ublock) for my cloud.

**Comment by sualko** [comment]
Ok, disabling and enabling of the app + no adblocker should resolve the issue. It's not satisfying, but I have no idea how I could debug this.

**Comment by DrMurx** [comment]
> Ok, disabling and enabling of the app + no adblocker should resolve the issue. It's not satisfying, but I have no idea how I could debug this.

Many tracking blockers (ie uBlock Origin) block JavaScript files if the path contains the words `piwik` or `matomo`, so `piwik/js/settings/admin.js` is blocked too. 

What you could do is to add a little textbox to the settings, informing the admin about the impact of tracking blockers, and if `piwik/js/settings/admin.js` loads without any issues, it simply hides this textbox.

**Comment by sualko** [comment]
@DrMurx that's a nice idea. If you have time it would great if you could open a pull request for that.Should also be possible on the github website :wink:.

**Comment by DrMurx** [comment]
Here you go.

**Comment by DrMurx** [comment]
@sualko Here you go.
