### ISSUE TITLE
Thanks for updating to 0.4.0 :) but where has the admin panel moved to in NC13?

### ISSUE THREAD

**Issue by mannp** [sualko/cloud_piwik#55]
Thanks for keeping the app maintained :+1: 

I've just updated and I now cannot see the two config box to add the ID and URL.

Have they moved in this release?

Else its just been a long day!

**Comment by sualko** [comment]
It should be at the exact same location: Settings > Administration > Additional settings. Can you check your NC log for any related errors?

**Comment by thfree** [comment]
Так же пропало управление приложением, в логах нечего внятного не увидел.
Удаление и установка решило проблему.


Also management of the appendix was gone, in ravines there is nothing distinct did not see.
Removal and installation solved a problem.

**Comment by sualko** [comment]
This has been also reported in #53 and should therefor solve the issue.
