### ISSUE TITLE
[0.4.0] configuration not visible

### ISSUE THREAD

**Issue by tuxmaster** [sualko/cloud_piwik#58]
### Expected behavior
That the configuration are visible 

### Actual behavior
No configuration settings are shown 

### Steps to reproduce the behavior
1. Log in to the nextcoud site
2. search all admin options

### Environment
- **App version:**  0.4.0
- **Nextcloud version:** 13.0.1
- **Browser vendor and version:**  firefox 59.02
- **Any browser plugins enabled?**  addblock plus, no script
- **Is your Matomo installation working as expected?**  yes

#### Javascript

```
Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://XXX/core/vendor/core.js?v=6c495e14-0
Source-Map-Adresse: purify.min.js.map[Weitere Informationen]
```

#### Nextcloud

```
No
```

**Comment by sualko** [comment]
I assume you already added an exception to noscript, but also try to disable addblock or add your Nextcloud to the whitelist. If this doesn't help, please try to disable and enable ojsxc.

**Comment by tuxmaster** [comment]
It looks it was AB plus.
After update to the last version (3.0.4) the settings will shown.
