### ISSUE TITLE
No file tracking log after upgrading from v 0.3.2 to v 0.4.0

### ISSUE THREAD

**Issue by danielepercivaldi** [sualko/cloud_piwik#59]
### Expected behavior
Browsing Nextcloud all actions are logged by matomo

### Actual behavior
Browsing Nextcloud no action about file tracking is logged by matomo (only dir, app, users and settings).

### Steps to reproduce the behavior
Upgrade from cloud_piwik 0.3.2 to 0.4.0

### Environment
- **App version:** 0.4.0
- **Nextcloud version:**13.0.2 
- **Browser vendor and version:** Google Chrome Versione 65.0.3325.181, Firefox 59.02
- **Any browser plugins enabled?** 
- **Is your Matomo installation working as expected?** Yes

#### Javascript
 
No error in console

#### Nextcloud

No error log in Nextcloud

#### Workaround
Backed to version 0.3.2

**Comment by sualko** [comment]
Have you tried turn it off and on again? :smile: Same users reported before that disabling and enabling the app solves your issue.

**Comment by gema2007** [comment]
I have the same problem. No logs arrive at Matomo
Ubuntu 16.04
Nextcloud 13.0.2

**Comment by davidv92** [comment]
I have the same problem.
What is the simplest way to come back to version 0.3.2 ?

**Comment by sualko** [comment]
I'm sorry guys, but without logs I can't help. Did you try to increase the log level?

**Comment by danielepercivaldi** [comment]
Hi @sualko.
I've just:
1. deleted log file
2. restarted apache
3.browsed some folders
4.open one image
5.downloaded the log file
Hope it can help you.

[nextcloud.log](https://github.com/sualko/cloud_piwik/files/1985467/nextcloud.log)

**Comment by sualko** [comment]
Can you check if `/apps/piwik/js/track.js` is loaded/included? Just open the the source code of any Nextcloud page (mostly ctrl+u). Can you also check if you have any errors in your js console (ctrl+shift+i)?

**Comment by danielepercivaldi** [comment]
Hi @sualko .
Yes, /apps/piwik/js/track.js exists.
Yes, track.js is loaded.
No, no log about track.js.

**Comment by sualko** [comment]
@danielepercivaldi can you send the url to your Nextcloud instance to klaus@jsxc.org?

**Comment by sualko** [comment]
Ok, now I understand the issue better. I thought there is no action tracked at all, but it's "only" about file browsing actions which are not tracked. Not sure when I have time to look into this in more detail.

**Comment by danielepercivaldi** [comment]
Done. Uhm for me it's line 90. It does not work yet.
I also guess that I'm not able to CHANGE the configuration option "Track file browsing". It is checked and if I uncheck it the new value is not set and back to checked state. Are you sure you load app configuration?

**Comment by sualko** [comment]
Can you test the [latest release](https://github.com/sualko/cloud_piwik/releases/tag/v0.4.1)?

**Comment by danielepercivaldi** [comment]
Hi @sualko .
Well:
1. "track file browsing" checkbox is ok
2. tracking tracks folder browsing, NOT file, i.e. if I open an image it is not tracked. Is it right?

**Comment by sualko** [comment]
> tracking tracks folder browsing, NOT file, i.e. if I open an image it is not tracked. Is it right?

That's the intended behavior. Thanks for testing.
