### ISSUE TITLE
Piwik plugin doesn't work

### ISSUE THREAD

**Issue by tx7** [sualko/cloud_piwik#61]
Hello,

I'm running Matomo on Nginx, and I've spent many hours investigating the issue, but no luck.
I'm using NC v13. Matomo is running fine, but the tracker doesn't work at all.
I've entered the Site ID, and the tracking url in NC settings: //abc.mydomain.com:8443/ .

Need help.

**Comment by sualko** [comment]
> WARNING: Bug reports which don't use this template will be closed immediately!
