### ISSUE TITLE
Update for compatibility with nextcloud 16 needed

### ISSUE THREAD

**Issue by lemmy04** [sualko/cloud_piwik#68]
### Expected behavior

I expect the plugin to work

### Actual behavior

plugin does not work

### Steps to reproduce the behavior
1. Update nextcloud to version 16

### Environment
- 0.9.8
- 16.0
- any
- **Any browser plugins enabled?** 
- not when it comes to tracking my nextcloud; every other site works.

#### Nextcloud
app is listes as "not compatible with this nextcloud version"

**Comment by lemmy04** [comment]
"Enable untested app" seems to be a working workaround.

**Comment by sualko** [comment]
Can you test the newest release?

https://github.com/sualko/cloud_piwik/releases/tag/v0.5.2

**Comment by lemmy04** [comment]
it doesn't show as update for the installed app...

**Comment by sualko** [comment]
It would be great if you could manually update the app, before I ship it to all users.

**Comment by lemmy04** [comment]
Manually installed it by removing the old version and unpacking the tar.gz in the apps folder, ran occ upgrade. seems to be fine, and no more compatibility warning.

**Comment by sualko** [comment]
Thanks for testing :+1:
