### ISSUE TITLE
Feature Request : Track Uploads/Downloads (why not ?)

### ISSUE THREAD

**Issue by GuiGuiSoft** [sualko/cloud_piwik#72]
Hello,

I see that downloads are not tracked (for security reason I guess ?).
Could it be possible to track download/upload in an different way ? With Matomo events system maybe ?

My main purpose is to have easily historical statistics of NextCloud usage.
The monitoring system integrated to NextCloud just show the current situation (number of shares) but I don't know if there was 200 shares more 1 hour ago.

Regards.

**Comment by sualko** [comment]
> for security reason I guess ?

For privacy reasons.

> Could it be possible to track download/upload in an different way?

You can track everything if you like, but for privacy reasons this will not be implemented in this app. Sorry.

**Comment by WeeSee** [comment]
Please re-asses this issue. 

Why do privacy concerns disallow tracking of downloads?

**Comment by sualko** [comment]
> Even if I don't really understand where is the privacy issue if we just count the number of downloads and uploads (without any user name or file name associated).

Matomo will always associate the users profile if downloads are tracked. That's the idea of Matomo.
