### ISSUE TITLE
Not compatible with Nexcloud 18

### ISSUE THREAD

**Issue by fa-ribeiro** [sualko/cloud_piwik#73]
Hi,
Not compatible with Nexcloud 18.
The highest supported version still is NC 17:

https://github.com/sualko/cloud_piwik/blob/3232d2dce87d197cb4609aa7aeb6eae0e6ac7de1/appinfo/info.xml#L17

**Comment by e-LUNATIC** [comment]
> Hi,
> Not compatible with Nexcloud 18.
> The highest supported version still is NC 17:
> 
> https://github.com/sualko/cloud_piwik/blob/3232d2dce87d197cb4609aa7aeb6eae0e6ac7de1/appinfo/info.xml#L17

But it works together with NC 18.01
