### ISSUE TITLE
Add support for Nextcloud 19

### ISSUE THREAD

**Issue by much-doge** [sualko/cloud_piwik#75]
Nextcloud 19 has been recently released, it would be nice to have tracking enabled to those who recently upgraded their instance to version 19.0.0

**Comment by sualko** [comment]
Did you try to enable it anyway? Had no time to test it yet.

**Comment by much-doge** [comment]
I just set up a staging instance, I'll try to see if it works

**Comment by much-doge** [comment]
> Did you try to enable it anyway? Had no time to test it yet.

I just set up a staging instance, I'll try to see if it works

**Comment by ajs124** [comment]
Seems to work fine for me.

**Comment by slawa-dev** [comment]
Regular users start getting Nextcloud 19.0.1 update. Need to bump the supported version.

**Comment by sualko** [comment]
Sorry, that you had to wait that long.
