### ISSUE TITLE
Matomo isn't tracking calls

### ISSUE THREAD

**Issue by LarsK1** [sualko/cloud_piwik#78]
### Expected behavior
Send a request to matomo, and process the request

### Actual behavior
request is sent but no tracking is recognized on Matomo

### Steps to reproduce the behavior
1. Call any Nextcloud page
2. Called URL: https://analyse.steuerberater-bayreuth.com/piwik.php?action_name=Dateien%20-%20Dateiupload%20STBK&idsite=2&rec=1&r=578658&h=8&m=38&s=6&url=https%3A%2F%2Fdateien.steuerberater-bayreuth.com%2Findex.php%2Fapps%2Ffiles%2F%3Fdir%3D%2F&uid=LarsKusch&_id=5c3ffcdfa691ced9&_idts=1599902015&_idvc=3&_idn=0&_refts=0&_viewts=1600012615&send_image=1&pdf=1&qt=0&realp=0&wma=0&dir=0&fla=0&java=0&gears=0&ag=0&cookie=1&res=1920x1080&cvar=%7B%221%22%3A%5B%22App%22%2C%22files%22%5D%7D&gt_ms=185&pv_id=8lomi4

### Environment
- **App version:** 0.6.0
- **Nextcloud version:**  19.0.3
- **Browser vendor and version:** Edge Chromium
- **Any browser plugins enabled?** No
- **Is your Matomo installation working as expected?** Yes

#### Javascript

No

**Comment by sualko** [comment]
Sorry, but this is likely an issue with your Matomo installation, because if the request is out, it seams everything is working fine from our side.
