### ISSUE TITLE
Mobile Track from nextcloud Module

### ISSUE THREAD

**Issue by ThibautMo** [sualko/cloud_piwik#79]
Hi,

The Matomo module for Nextcloud no longer works correctly, mobile tracking no longer returns any information 

1. Tracking visits from public link
2.
3.

### Environment
- **App version: 0.7
- **Nextcloud version:19.0.3 AND 20
- ALL Mobile browser from public links
- **Any browser plugins enabled? No 
- **Is your Matomo installation working as expected? Yes 2 installation of matomo and it fonction correctly from other sites 

#### Javascript
No erreors in javascript
```
```

#### Nextcloud
No errors in logs

**Comment by sualko** [comment]
Probably related to #80, otherwise not enough information is provided.
