### ISSUE TITLE
Nextcloud 22 support

### ISSUE THREAD

**Issue by minils** [sualko/cloud_piwik#84]
Nextcloud 22 is out, so it would be nice if you could update to support the new version :slightly_smiling_face:

**Comment by wisobe** [comment]
Anyone tried updating Nextcloud without Nextcloud 22 support ? Will it work ?

**Comment by dwydler** [comment]
> Anyone tried updating Nextcloud without Nextcloud 22 support ? Will it work ?
Does everyone try it out?

**Comment by wisobe** [comment]
> > Anyone tried updating Nextcloud without Nextcloud 22 support ? Will it work ?
> > Does everyone try it out?

It works just fine on my side. :-)
