### ISSUE TITLE
Unable to install latest version `0.11.0`

### ISSUE THREAD

**Issue by JFossey** [sualko/cloud_piwik#96]
### Expected behavior

Installing or Upgrading to latest version `0.11.0`.

### Actual behavior

Only able to install version `0.10.0` and `occ` only detects the beta version and fails.

``` sh
php occ app:update piwik --allow-unstable
piwik new version available: 0.11.0-beta.1
piwik couldn't be updated
```

### Steps to reproduce the behavior

1. Nextcloud release set to stable
2. Install `Piwik/Matomo Tracking` via UI
3. Version `0.10.0` is installed

### Environment
- **App version:** 0.10.0
- **Nextcloud version:** 25

**Comment by sualko** [comment]
Sorry for the inconvenience. I could not upload the latest release to the app store when I released it. Seams like Nextcloud fixed the bug and therefore you should find 0.11.1 there now. Have fun.
