### ISSUE TITLE
Support for NC 26

### ISSUE THREAD

**Issue by RunnerLexico** [sualko/cloud_piwik#99]
Nextcloud 26 is out and the piwik app is not compatible yet.

Does it work with Nextcloud 26?

Thanks and regards

**Comment by SimJoSt** [comment]
I reached out to @sualko, and he seems to have some time shortly to work on this: https://fosstodon.org/@sualko/110784953583878800

**Comment by sualko** [comment]
Please test the current release. If you find any problems, please open an issue.

@SimJoSt thanks for your support
